import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useUserProfile } from "@/hooks/useUserProfile";
import { format } from "date-fns";

interface RecipeInfoDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  sourceUrl?: string;
  importMethod?: string;
  createdBy?: string;
  createdAt?: string;
  updatedAt?: string;
  lastUpdatedBy?: string;
}

export const RecipeInfoDialog = ({
  open,
  onOpenChange,
  sourceUrl,
  importMethod,
  createdBy,
  createdAt,
  updatedAt,
  lastUpdatedBy
}: RecipeInfoDialogProps) => {
  const { profile: createdByProfile } = useUserProfile(createdBy || null);
  const { profile: updatedByProfile } = useUserProfile(lastUpdatedBy || null);
  
  const formatDate = (dateString?: string) => {
    if (!dateString) return '';
    try {
      return format(new Date(dateString), 'MMMM d, yyyy');
    } catch {
      return dateString;
    }
  };

  const getImportMethodText = () => {
    if (!importMethod) return '';
    
    switch (importMethod) {
      case 'url':
        return 'Imported from URL';
      case 'text':
        return 'Imported from text';
      case 'image':
        return 'Imported from image';
      case 'ai_generated':
        return 'Generated by AI';
      default:
        return 'Created manually';
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-sm bg-white">
        <DialogHeader>
          <DialogTitle className="text-center">Recipe Info</DialogTitle>
        </DialogHeader>
        <div className="py-4 space-y-3">
          {createdAt && (
            <p className="text-sm text-muted-foreground text-center">
              Created {formatDate(createdAt)}
              {createdByProfile?.full_name && ` by ${createdByProfile.full_name}`}
            </p>
          )}
          
          {updatedAt && updatedAt !== createdAt && (
            <p className="text-sm text-muted-foreground text-center">
              Last updated {formatDate(updatedAt)}
              {updatedByProfile?.full_name && ` by ${updatedByProfile.full_name}`}
            </p>
          )}
          
          {importMethod && (
            <p className="text-sm text-muted-foreground text-center">
              {getImportMethodText()}
            </p>
          )}
          
          {sourceUrl && (
            <div className="text-center">
              <a 
                href={sourceUrl} 
                target="_blank" 
                rel="noopener noreferrer"
                className="text-sm text-blue-600 hover:text-blue-800 underline break-all"
              >
                View original source
              </a>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};