import { useState, useEffect, useCallback, useRef } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { useHousehold } from "@/contexts/HouseholdContext";
import { useToast } from "@/hooks/use-toast";
import { ShoppingListItem } from "@/types/shoppingList";
import { ShoppingListService } from "@/services/shoppingListService";
import { supabase } from "@/integrations/supabase/client";

export const useShoppingList = (weekKey: string) => {
  const { user } = useAuth();
  const { currentHousehold } = useHousehold();
  const { toast } = useToast();
  
  const [shoppingList, setShoppingList] = useState<ShoppingListItem[]>([]);
  // Remove isLoading - never expose it, load happens silently
  
  const loadShoppingList = useCallback(async () => {
    if (!user || !currentHousehold) return;

    // Load silently - no loading state, just update when data arrives
    try {
      const items = await ShoppingListService.loadExistingShoppingList(currentHousehold.id, weekKey);
      console.log('Loaded shopping list items:', items);
      setShoppingList(items);
    } catch (error) {
      console.error("Error loading shopping list:", error);
      setShoppingList([]);
    }
  }, [user, currentHousehold, weekKey]);

  // Real-time subscription: refresh for external changes, but keep checkbox updates local.
  useEffect(() => {
    if (!currentHousehold) return;

    let debounceTimer: NodeJS.Timeout | null = null;

    const channel = supabase
      .channel(`shopping-list-changes-week-${weekKey}`)
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'household_shopping_lists',
          filter: `household_id=eq.${currentHousehold.id}.and.week_key=eq.${weekKey}`
        },
        (payload) => {
          console.log('Shopping list changed for week', weekKey, ':', payload);

          // Our checkbox updates are already applied optimistically, so do not reload
          // the entire list for UPDATE events. Reload INSERT/DELETE events so changes
          // from other devices/users are reflected.
          if (payload.eventType === 'UPDATE') {
            return;
          }

          if (debounceTimer) {
            clearTimeout(debounceTimer);
          }

          debounceTimer = setTimeout(() => {
            loadShoppingList();
          }, 150);
        }
      )
      .subscribe();

    // Listen for auto-generation completion events
    const handleAutoGenerated = (event: CustomEvent) => {
      if (event.detail.weekKey === weekKey) {
        console.log('Auto-generation completed for week', weekKey, '- refreshing list');
        loadShoppingList();
      }
    };

    window.addEventListener('shopping-list-auto-generated', handleAutoGenerated as EventListener);

    return () => {
      if (debounceTimer) {
        clearTimeout(debounceTimer);
      }
      window.removeEventListener('shopping-list-auto-generated', handleAutoGenerated as EventListener);
      supabase.removeChannel(channel);
    };
  }, [currentHousehold, loadShoppingList, weekKey]);

  useEffect(() => {
    loadShoppingList();
  }, [loadShoppingList]);

  const toggleItemChecked = useCallback(async (itemId: string) => {
    if (!user || !currentHousehold) return;

    // Read from the latest state inside the updater so rapid consecutive taps
    // never rely on a stale shoppingList closure.
    let newCheckedState: boolean | null = null;

    setShoppingList(prev => prev.map(i => {
      if (i.id !== itemId) return i;
      newCheckedState = !i.isChecked;
      return { ...i, isChecked: newCheckedState };
    }));

    if (newCheckedState === null) return;

    // Update database without reloading the list afterwards.
    const success = await ShoppingListService.toggleItemChecked(
      itemId,
      newCheckedState,
      currentHousehold.id
    );
    
    if (!success) {
      // Revert on error.
      setShoppingList(prev => prev.map(i =>
        i.id === itemId ? { ...i, isChecked: !newCheckedState } : i
      ));
      
      toast({
        title: "Error",
        description: "Failed to update item",
        variant: "destructive",
      });
    }
  }, [user, currentHousehold, toast]);

  const addCustomItem = useCallback(async (name: string) => {
    if (!user || !currentHousehold || !name.trim()) return;

    const newItem = await ShoppingListService.addCustomItem(name, currentHousehold.id, user.id, weekKey);
    
    if (newItem) {
      // Add new items to the top of the list
      setShoppingList(prev => [newItem, ...prev]);

      toast({
        title: "Item added",
        description: `${name} added to shopping list`,
      });
    } else {
      toast({
        title: "Error",
        description: "Failed to add item",
        variant: "destructive",
      });
    }
  }, [user, currentHousehold, toast, weekKey]);

  const updateItem = useCallback(async (itemId: string, newName: string) => {
    if (!user || !currentHousehold || !newName.trim()) return;

    const oldItem = shoppingList.find(i => i.id === itemId);
    if (!oldItem) return;

    // Update local state immediately
    setShoppingList(prev => prev.map(i => 
      i.id === itemId ? { ...i, name: newName.trim() } : i
    ));

    // Update database
    const success = await ShoppingListService.updateItem(itemId, newName, currentHousehold.id);
    
    if (!success) {
      // Revert on error
      setShoppingList(prev => prev.map(i => 
        i.id === itemId ? { ...i, name: oldItem.name } : i
      ));
      
      toast({
        title: "Error",
        description: "Failed to update item",
        variant: "destructive",
      });
    }
  }, [user, currentHousehold, shoppingList, toast]);

  const clearAll = useCallback(async () => {
    if (!user || !currentHousehold) return;

    // Clear UI immediately
    setShoppingList([]);
    
    try {
      const success = await ShoppingListService.clearAll(currentHousehold.id, weekKey);
      
      if (!success) {
        // Reload on error to restore actual state
        await loadShoppingList();
        toast({
          title: "Error",
          description: "Failed to clear shopping list",
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error("Error clearing shopping list:", error);
      // Reload on error to restore actual state
      await loadShoppingList();
      toast({
        title: "Error",
        description: "Failed to clear shopping list",
        variant: "destructive",
      });
    }
  }, [user, currentHousehold, weekKey, loadShoppingList, toast]);

  return {
    shoppingList,
    // Remove isLoading from return - never expose it
    toggleItemChecked,
    addCustomItem,
    updateItem,
    clearAll,
    refreshList: loadShoppingList,
  };
};
