import { useState, useEffect, useCallback, useRef } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { useHousehold } from "@/contexts/HouseholdContext";
import { useToast } from "@/hooks/use-toast";
import { ShoppingListItem } from "@/types/shoppingList";
import { ShoppingListService } from "@/services/shoppingListService";
import { supabase } from "@/integrations/supabase/client";

type ShoppingListUpdater =
  | ShoppingListItem[]
  | ((previous: ShoppingListItem[]) => ShoppingListItem[]);

export const useShoppingList = (weekKey: string) => {
  const { user } = useAuth();
  const { currentHousehold } = useHousehold();
  const { toast } = useToast();

  const [shoppingList, setShoppingList] = useState<ShoppingListItem[]>([]);
  // Keep a synchronous copy for event handlers. React state updater callbacks
  // are not guaranteed to execute before the caller continues.
  const shoppingListRef = useRef<ShoppingListItem[]>([]);
  const pendingCheckedValuesRef = useRef<Map<string, boolean>>(new Map());
  const persistedCheckedValuesRef = useRef<Map<string, boolean>>(new Map());
  const toggleSaveQueuesRef = useRef<Map<string, Promise<void>>>(new Map());
  const toggleRequestSequenceRef = useRef<Map<string, number>>(new Map());
  // Prevent a list read started before a checkbox mutation from overwriting
  // that newer optimistic state when the read eventually resolves.
  const listMutationVersionRef = useRef(0);

  const updateShoppingList = useCallback((nextOrUpdater: ShoppingListUpdater) => {
    const next =
      typeof nextOrUpdater === "function"
        ? nextOrUpdater(shoppingListRef.current)
        : nextOrUpdater;
    shoppingListRef.current = next;
    setShoppingList(next);
  }, []);

  const loadShoppingList = useCallback(async () => {
    if (!user || !currentHousehold) return;

    const loadVersion = listMutationVersionRef.current;
    try {
      const items = await ShoppingListService.loadExistingShoppingList(currentHousehold.id, weekKey);

      // A checkbox was changed while this read was in flight. Its response may
      // contain an older is_checked value, so leave the newer state untouched.
      if (loadVersion !== listMutationVersionRef.current) return;

      items.forEach(item => {
        if (!pendingCheckedValuesRef.current.has(item.id)) {
          persistedCheckedValuesRef.current.set(item.id, item.isChecked);
        }
      });

      // Reads that begin during a pending write should not flash the old checked
      // value back into the UI while the save is in progress.
      const itemsWithPendingChecks = items.map(item => {
        const pendingValue = pendingCheckedValuesRef.current.get(item.id);
        return pendingValue === undefined ? item : { ...item, isChecked: pendingValue };
      });

      console.log("Loaded shopping list items:", itemsWithPendingChecks);
      updateShoppingList(itemsWithPendingChecks);
    } catch (error) {
      console.error("Error loading shopping list:", error);
      // A failed read is not an empty list. Keep the last known items visible
      // instead of replacing them with an empty array on transient errors.
    }
  }, [user, currentHousehold, weekKey, updateShoppingList]);

  // Real-time subscription: refresh for external changes, but keep checkbox updates local.
  useEffect(() => {
    if (!currentHousehold) return;

    let debounceTimer: ReturnType<typeof setTimeout> | null = null;

    const channel = supabase
      .channel("shopping-list-changes-household-" + currentHousehold.id + "-week-" + weekKey)
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "household_shopping_lists",
          // Postgres Changes supports a single filter here; filter by household
          // and narrow to the selected week in the callback below.
          filter: "household_id=eq." + currentHousehold.id
        },
        (payload) => {
          console.log("Shopping list changed for week", weekKey, ":", payload);

          // Filter by week locally because Postgres Changes accepts only one
          // subscription filter. Re-read UPDATE events too, so other household
          // members' checkbox changes are reflected on this device.
          const changedRow = payload.eventType === "DELETE" ? payload.old : payload.new;
          if (
            changedRow &&
            typeof changedRow.week_key === "string" &&
            changedRow.week_key !== weekKey
          ) {
            return;
          }

          if (debounceTimer) clearTimeout(debounceTimer);
          debounceTimer = setTimeout(() => {
            void loadShoppingList();
          }, 150);
        }
      )
      .subscribe();

    const handleAutoGenerated = (event: CustomEvent) => {
      if (event.detail.weekKey === weekKey) {
        console.log("Auto-generation completed for week", weekKey, "- refreshing list");
        void loadShoppingList();
      }
    };

    window.addEventListener("shopping-list-auto-generated", handleAutoGenerated as EventListener);

    return () => {
      if (debounceTimer) clearTimeout(debounceTimer);
      window.removeEventListener("shopping-list-auto-generated", handleAutoGenerated as EventListener);
      void supabase.removeChannel(channel);
    };
  }, [currentHousehold, loadShoppingList, weekKey]);

  useEffect(() => {
    void loadShoppingList();
  }, [loadShoppingList]);

  const toggleItemChecked = useCallback(async (itemId: string) => {
    if (!user || !currentHousehold) return;

    // Calculate the next value outside a React state updater. Performing side
    // effects from inside a functional updater is unsafe because React may defer
    // or replay it; previously that could leave newCheckedState null and skip the
    // database write entirely.
    const currentItem = shoppingListRef.current.find(item => item.id === itemId);
    if (!currentItem) return;

    const newCheckedState = !currentItem.isChecked;
    const requestSequence = (toggleRequestSequenceRef.current.get(itemId) ?? 0) + 1;
    toggleRequestSequenceRef.current.set(itemId, requestSequence);
    if (!persistedCheckedValuesRef.current.has(itemId)) {
      persistedCheckedValuesRef.current.set(itemId, currentItem.isChecked);
    }

    listMutationVersionRef.current += 1;
    pendingCheckedValuesRef.current.set(itemId, newCheckedState);
    updateShoppingList(previous =>
      previous.map(item => item.id === itemId ? { ...item, isChecked: newCheckedState } : item)
    );

    // Serialize writes per item so fast repeated taps cannot reach the database
    // out of order and leave an older value as the final persisted state.
    const previousSave = toggleSaveQueuesRef.current.get(itemId) ?? Promise.resolve();
    const saveTask = previousSave.catch(() => undefined).then(async () => {
      const success = await ShoppingListService.toggleItemChecked(
        itemId,
        newCheckedState,
        currentHousehold.id
      );

      listMutationVersionRef.current += 1;

      if (success) {
        persistedCheckedValuesRef.current.set(itemId, newCheckedState);
        if (
          toggleRequestSequenceRef.current.get(itemId) === requestSequence &&
          pendingCheckedValuesRef.current.get(itemId) === newCheckedState
        ) {
          pendingCheckedValuesRef.current.delete(itemId);
        }
        return;
      }

      // Only roll back if this failed write still represents the user's latest
      // requested value. A newer tap should win over an older request's failure.
      if (
        toggleRequestSequenceRef.current.get(itemId) === requestSequence &&
        pendingCheckedValuesRef.current.get(itemId) === newCheckedState
      ) {
        pendingCheckedValuesRef.current.delete(itemId);
        const persistedValue = persistedCheckedValuesRef.current.get(itemId) ?? currentItem.isChecked;
        updateShoppingList(previous =>
          previous.map(item =>
            item.id === itemId && item.isChecked === newCheckedState
              ? { ...item, isChecked: persistedValue }
              : item
          )
        );

        toast({
          title: "Error",
          description: "Failed to update item",
          variant: "destructive",
        });
      }
    });

    toggleSaveQueuesRef.current.set(itemId, saveTask);
    try {
      await saveTask;
    } finally {
      if (toggleSaveQueuesRef.current.get(itemId) === saveTask) {
        toggleSaveQueuesRef.current.delete(itemId);
      }
    }
  }, [user, currentHousehold, toast, updateShoppingList]);

  const addCustomItem = useCallback(async (name: string) => {
    if (!user || !currentHousehold || !name.trim()) return;

    const newItem = await ShoppingListService.addCustomItem(name, currentHousehold.id, user.id, weekKey);

    if (newItem) {
      updateShoppingList(previous => [newItem, ...previous]);
      persistedCheckedValuesRef.current.set(newItem.id, newItem.isChecked);
      toast({
        title: "Item added",
        description: name + " added to shopping list",
      });
    } else {
      toast({
        title: "Error",
        description: "Failed to add item",
        variant: "destructive",
      });
    }
  }, [user, currentHousehold, toast, weekKey, updateShoppingList]);

  const updateItem = useCallback(async (itemId: string, newName: string) => {
    if (!user || !currentHousehold || !newName.trim()) return;

    const oldItem = shoppingListRef.current.find(item => item.id === itemId);
    if (!oldItem) return;

    updateShoppingList(previous =>
      previous.map(item => item.id === itemId ? { ...item, name: newName.trim() } : item)
    );

    const success = await ShoppingListService.updateItem(itemId, newName, currentHousehold.id);

    if (!success) {
      updateShoppingList(previous =>
        previous.map(item => item.id === itemId ? { ...item, name: oldItem.name } : item)
      );
      toast({
        title: "Error",
        description: "Failed to update item",
        variant: "destructive",
      });
    }
  }, [user, currentHousehold, toast, updateShoppingList]);

  const clearAll = useCallback(async () => {
    if (!user || !currentHousehold) return;

    updateShoppingList([]);
    try {
      const success = await ShoppingListService.clearAll(currentHousehold.id, weekKey);

      if (!success) {
        await loadShoppingList();
        toast({
          title: "Error",
          description: "Failed to clear shopping list",
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error("Error clearing shopping list:", error);
      await loadShoppingList();
      toast({
        title: "Error",
        description: "Failed to clear shopping list",
        variant: "destructive",
      });
    }
  }, [user, currentHousehold, weekKey, loadShoppingList, toast, updateShoppingList]);

  return {
    shoppingList,
    toggleItemChecked,
    addCustomItem,
    updateItem,
    clearAll,
    refreshList: loadShoppingList,
  };
};
