import { IngredientCategory } from "@/types/ingredientCategories";

/**
 * Offline guide list for ingredient categorization
 * Used as a fallback when OpenAI is unavailable or for offline mode
 * Format: ingredient name (normalized, lowercase) -> category
 */
export const INGREDIENT_CATEGORY_GUIDE: Record<string, IngredientCategory> = {
  // Fruit & Vegetables
  "apple": "Fruit & Vegetables",
  "apples": "Fruit & Vegetables",
  "banana": "Fruit & Vegetables",
  "bananas": "Fruit & Vegetables",
  "orange": "Fruit & Vegetables",
  "oranges": "Fruit & Vegetables",
  "strawberry": "Fruit & Vegetables",
  "strawberries": "Fruit & Vegetables",
  "blueberry": "Fruit & Vegetables",
  "blueberries": "Fruit & Vegetables",
  "raspberry": "Fruit & Vegetables",
  "raspberries": "Fruit & Vegetables",
  "grape": "Fruit & Vegetables",
  "grapes": "Fruit & Vegetables",
  "tomato": "Fruit & Vegetables",
  "tomatoes": "Fruit & Vegetables",
  "lettuce": "Fruit & Vegetables",
  "spinach": "Fruit & Vegetables",
  "carrot": "Fruit & Vegetables",
  "carrots": "Fruit & Vegetables",
  "onion": "Fruit & Vegetables",
  "onions": "Fruit & Vegetables",
  "garlic": "Fruit & Vegetables",
  "potato": "Fruit & Vegetables",
  "potatoes": "Fruit & Vegetables",
  "pepper": "Fruit & Vegetables",
  "peppers": "Fruit & Vegetables",
  "cucumber": "Fruit & Vegetables",
  "cucumbers": "Fruit & Vegetables",
  "broccoli": "Fruit & Vegetables",
  "cauliflower": "Fruit & Vegetables",
  "cabbage": "Fruit & Vegetables",
  "celery": "Fruit & Vegetables",
  "mushroom": "Fruit & Vegetables",
  "mushrooms": "Fruit & Vegetables",
  "avocado": "Fruit & Vegetables",
  "avocados": "Fruit & Vegetables",
  "lemon": "Fruit & Vegetables",
  "lemons": "Fruit & Vegetables",
  "lime": "Fruit & Vegetables",
  "limes": "Fruit & Vegetables",
  "herbs": "Fruit & Vegetables",
  "basil": "Fruit & Vegetables",
  "parsley": "Fruit & Vegetables",
  "coriander": "Fruit & Vegetables",
  "mint": "Fruit & Vegetables",
  "thyme": "Fruit & Vegetables",
  "rosemary": "Fruit & Vegetables",
  "oregano": "Fruit & Vegetables",

  // Meat & Fish
  "bacon": "Meat & Fish",
  "beef": "Meat & Fish",
  "chicken": "Meat & Fish",
  "pork": "Meat & Fish",
  "lamb": "Meat & Fish",
  "turkey": "Meat & Fish",
  "duck": "Meat & Fish",
  "sausage": "Meat & Fish",
  "sausages": "Meat & Fish",
  "mince": "Meat & Fish",
  "minced beef": "Meat & Fish",
  "minced pork": "Meat & Fish",
  "steak": "Meat & Fish",
  "salmon": "Meat & Fish",
  "tuna": "Meat & Fish",
  "cod": "Meat & Fish",
  "haddock": "Meat & Fish",
  "prawns": "Meat & Fish",
  "shrimp": "Meat & Fish",
  "crab": "Meat & Fish",
  "lobster": "Meat & Fish",
  "mussels": "Meat & Fish",
  "oysters": "Meat & Fish",
  "fish": "Meat & Fish",
  "seafood": "Meat & Fish",

  // Chilled Food
  "milk": "Chilled Food",
  "cheese": "Chilled Food",
  "cheddar": "Chilled Food",
  "mozzarella": "Chilled Food",
  "butter": "Chilled Food",
  "cream": "Chilled Food",
  "double cream": "Chilled Food",
  "single cream": "Chilled Food",
  "yogurt": "Chilled Food",
  "yoghurt": "Chilled Food",
  "greek yogurt": "Chilled Food",
  "eggs": "Chilled Food",
  "egg": "Chilled Food",
  "mayonnaise": "Chilled Food",
  "sour cream": "Chilled Food",
  "cream cheese": "Chilled Food",
  "cottage cheese": "Chilled Food",
  "ready meal": "Chilled Food",
  "ready meals": "Chilled Food",
  "deli": "Chilled Food",

  // Bakery
  "bread": "Bakery",
  "white bread": "Bakery",
  "brown bread": "Bakery",
  "wholemeal bread": "Bakery",
  "baguette": "Bakery",
  "rolls": "Bakery",
  "buns": "Bakery",
  "croissant": "Bakery",
  "croissants": "Bakery",
  "pastry": "Bakery",
  "pastries": "Bakery",
  "puff pastry": "Bakery",
  "shortcrust pastry": "Bakery",
  "cake": "Bakery",
  "cakes": "Bakery",

  // Frozen Food
  "frozen peas": "Frozen Food",
  "frozen vegetables": "Frozen Food",
  "frozen berries": "Frozen Food",
  "ice cream": "Frozen Food",
  "frozen pizza": "Frozen Food",
  "frozen ready meal": "Frozen Food",
  "frozen ready meals": "Frozen Food",
  "frozen fish": "Frozen Food",
  "frozen meat": "Frozen Food",

  // Food Cupboard
  "flour": "Food Cupboard",
  "plain flour": "Food Cupboard",
  "self raising flour": "Food Cupboard",
  "sugar": "Food Cupboard",
  "brown sugar": "Food Cupboard",
  "caster sugar": "Food Cupboard",
  "icing sugar": "Food Cupboard",
  "salt": "Food Cupboard",
  "pepper": "Food Cupboard",
  "black pepper": "Food Cupboard",
  "olive oil": "Food Cupboard",
  "vegetable oil": "Food Cupboard",
  "sunflower oil": "Food Cupboard",
  "cooking oil": "Food Cupboard",
  "pasta": "Food Cupboard",
  "spaghetti": "Food Cupboard",
  "penne": "Food Cupboard",
  "rice": "Food Cupboard",
  "basmati rice": "Food Cupboard",
  "brown rice": "Food Cupboard",
  "canned tomatoes": "Food Cupboard",
  "tinned tomatoes": "Food Cupboard",
  "canned beans": "Food Cupboard",
  "tinned beans": "Food Cupboard",
  "baked beans": "Food Cupboard",
  "kidney beans": "Food Cupboard",
  "chickpeas": "Food Cupboard",
  "lentils": "Food Cupboard",
  "stock": "Food Cupboard",
  "chicken stock": "Food Cupboard",
  "vegetable stock": "Food Cupboard",
  "stock cube": "Food Cupboard",
  "stock cubes": "Food Cupboard",
  "spices": "Food Cupboard",
  "cumin": "Food Cupboard",
  "paprika": "Food Cupboard",
  "turmeric": "Food Cupboard",
  "cinnamon": "Food Cupboard",
  "nutmeg": "Food Cupboard",
  "vanilla extract": "Food Cupboard",
  "baking powder": "Food Cupboard",
  "bicarbonate of soda": "Food Cupboard",
  "baking soda": "Food Cupboard",
  "yeast": "Food Cupboard",
  "vinegar": "Food Cupboard",
  "balsamic vinegar": "Food Cupboard",
  "soy sauce": "Food Cupboard",
  "worcestershire sauce": "Food Cupboard",
  "honey": "Food Cupboard",
  "jam": "Food Cupboard",
  "marmalade": "Food Cupboard",
  "peanut butter": "Food Cupboard",
  "nuts": "Food Cupboard",
  "almonds": "Food Cupboard",
  "walnuts": "Food Cupboard",
  "coconut": "Food Cupboard",
  "coconut milk": "Food Cupboard",
  "coconut cream": "Food Cupboard",

  // Snacks & Treats
  "chocolate": "Snacks & Treats",
  "dark chocolate": "Snacks & Treats",
  "milk chocolate": "Snacks & Treats",
  "crisps": "Snacks & Treats",
  "chips": "Snacks & Treats",
  "crackers": "Snacks & Treats",
  "biscuits": "Snacks & Treats",
  "cookies": "Snacks & Treats",
  "sweets": "Snacks & Treats",
  "candy": "Snacks & Treats",
  "popcorn": "Snacks & Treats",
  "nuts": "Snacks & Treats",
  "peanuts": "Snacks & Treats",
  "cashews": "Snacks & Treats",

  // World & Dietary
  "tofu": "World & Dietary",
  "tempeh": "World & Dietary",
  "quinoa": "World & Dietary",
  "chia seeds": "World & Dietary",
  "flax seeds": "World & Dietary",
  "coconut oil": "World & Dietary",
  "tahini": "World & Dietary",
  "miso": "World & Dietary",
  "kimchi": "World & Dietary",
  "sauerkraut": "World & Dietary",
  "gluten free": "World & Dietary",
  "vegan": "World & Dietary",
  "organic": "World & Dietary",

  // Drinks
  "water": "Drinks",
  "juice": "Drinks",
  "orange juice": "Drinks",
  "apple juice": "Drinks",
  "soft drink": "Drinks",
  "soft drinks": "Drinks",
  "cola": "Drinks",
  "lemonade": "Drinks",
  "tea": "Drinks",
  "coffee": "Drinks",
  "instant coffee": "Drinks",
  "ground coffee": "Drinks",
  "coffee beans": "Drinks",
  "herbal tea": "Drinks",
  "green tea": "Drinks",
  "black tea": "Drinks",
  "smoothie": "Drinks",
  "smoothies": "Drinks",

  // Alcohol
  "wine": "Alcohol",
  "red wine": "Alcohol",
  "white wine": "Alcohol",
  "rosé wine": "Alcohol",
  "beer": "Alcohol",
  "lager": "Alcohol",
  "ale": "Alcohol",
  "spirits": "Alcohol",
  "whisky": "Alcohol",
  "whiskey": "Alcohol",
  "vodka": "Alcohol",
  "gin": "Alcohol",
  "rum": "Alcohol",
  "brandy": "Alcohol",
  "liqueur": "Alcohol",
  "liqueurs": "Alcohol",
  "champagne": "Alcohol",
  "prosecco": "Alcohol",
  "cider": "Alcohol",
};

/**
 * Get category for an ingredient from the guide (offline fallback)
 */
export function getCategoryFromGuide(ingredientName: string): IngredientCategory | null {
  const normalized = ingredientName.toLowerCase().trim();
  return INGREDIENT_CATEGORY_GUIDE[normalized] || null;
}
