
export const FUNNY_LOADING_MESSAGES = [
  "🤓 Oh where did I put my reading glasses...",
  "😋 WOW this recipe looks tasty!",
  "🤤 Getting peckish just looking at this...",
  "🕵️ Investigating kitchen mysteries...",
  "🎭 Putting on my chef hat...",
  "🦸 Activating recipe superpowers...",
  "🔮 Consulting the culinary crystal ball...",
  "🎪 Performing food magic tricks...",
  "🧙‍♂️ Brewing up some recipe wizardry...",
  "🎯 Hunting for flavour treasures...",
  "👨‍🍳 Donning my apron with style...",
  "🍴 Preparing the finest cutlery...",
  "🥄 Stirring up some culinary magic...",
  "🌟 Sprinkling fairy dust on ingredients...",
  "🔍 Analysing the art of cookery...",
  "🎨 Painting flavours on the palette...",
  "🏆 Competing for the best recipe prize...",
  "🚀 Launching into flavour space...",
  "🎭 Rehearsing the cooking performance...",
  "🎪 Juggling ingredients with finesse..."
];

export const SUPPORTED_DOMAINS = [
  'allrecipes.com',
  'food.com',
  'foodnetwork.com',
  'epicurious.com',
  'bonappetit.com',
  'delish.com',
  'eatingwell.com',
  'foodandwine.com',
  'myrecipes.com',
  'taste.com.au',
  'bbcgoodfood.com',
  'jamieoliver.com',
  'nigella.com',
  'recipetineats.com',
  'cafedelites.com',
  'therecipecritic.com',
  'cookieandkate.com',
  'minimalistbaker.com',
  'loveandlemons.com',
  'budgetbytes.com'
];
