-- Replace all daily cooking tips with UK-focused content
-- Covers: UK dishes, regional cuisines, seasonal produce, meat cuts, storage, freezing, meal prepping

DELETE FROM public.daily_cooking_tips;

INSERT INTO public.daily_cooking_tips (day_of_year, tip) VALUES
-- January (Days 1-31) - Winter produce, comfort foods, storage tips
(1, 'Start the year right: ask your local butcher for brisket – perfect for slow-cooked Sunday roasts'),
(2, 'Store root vegetables in a cool, dark place – they''ll last months if kept properly'),
(3, 'Freeze leftover Christmas turkey in portions – perfect for quick curries and pies'),
(4, 'Meal prep your Sunday roast vegetables on Saturday – parboil potatoes and prep carrots'),
(5, 'Your local butcher can recommend the best cut for beef stew – shin or chuck work brilliantly'),
(6, 'Store Brussels sprouts in the fridge for up to a week – they''re at their peak in January'),
(7, 'Freeze leftover gravy in ice cube trays – defrost one cube per portion for quick dinners'),
(8, 'Batch cook shepherd''s pie and freeze in portions – ideal for busy weeknights'),
(9, 'Ask your fishmonger for cod or haddock – perfect for proper fish and chips'),
(10, 'Store fresh herbs from your greengrocer upright in water in the fridge – they''ll last longer'),
(11, 'Freeze leftover mashed potato in portions – perfect for quick bubble and squeak'),
(12, 'Meal prep your weekday lunches on Sunday – make a big batch of soup or stew'),
(13, 'Your local butcher''s sausages are far superior to supermarket ones – support local businesses'),
(14, 'Store fresh fish on ice in the fridge and use within 24 hours for best quality'),
(15, 'Freeze leftover roast chicken carcasses – make stock when you have three or four'),
(16, 'Batch cook bolognese sauce and freeze – defrost for quick spaghetti dinners'),
(17, 'Ask your butcher for pork shoulder – slow-cooked, it makes incredible pulled pork'),
(18, 'Store potatoes away from onions – they''ll sprout faster if kept together'),
(19, 'Freeze leftover wine in ice cube trays – add to sauces and stews for depth'),
(20, 'Meal prep your breakfast – overnight oats or chia pudding saves morning time'),
(21, 'Your local farm shop will have the freshest seasonal vegetables – visit weekly'),
(22, 'Store fresh mushrooms in a paper bag, never plastic – prevents them going slimy'),
(23, 'Freeze leftover bread as breadcrumbs – blitz in food processor when frozen'),
(24, 'Batch cook curry pastes and freeze in portions – Thai green curry paste keeps for months'),
(25, 'Ask your fishmonger for whole fish – they''ll fillet it for you and it''s cheaper'),
(26, 'Store fresh ginger in the freezer – grate straight from frozen, no need to peel'),
(27, 'Freeze leftover cream in ice cube trays – perfect for adding to sauces'),
(28, 'Meal prep your Sunday roast – prep everything Saturday night for stress-free cooking'),
(29, 'Your local butcher can advise on best cuts for slow cooking – perfect for winter stews'),
(30, 'Store fresh citrus fruits at room temperature – they''ll last longer and taste better'),
(31, 'Freeze leftover Yorkshire pudding batter – it actually improves after freezing'),

-- February (Days 32-59) - Late winter, early spring prep
(32, 'Ask your butcher for lamb shanks – slow-cooked with red wine, they''re winter comfort food'),
(33, 'Store fresh leeks wrapped in damp kitchen paper in the fridge – they''ll keep for weeks'),
(34, 'Freeze leftover casserole portions – label with date and contents for easy meal planning'),
(35, 'Meal prep your week''s vegetables – wash, chop and store in airtight containers'),
(36, 'Your local greengrocer will have the best seasonal produce – ask what''s in season'),
(37, 'Store fresh herbs in the fridge wrapped in damp kitchen paper – change paper every few days'),
(38, 'Freeze leftover stew in individual portions – perfect for solo dinners or packed lunches'),
(39, 'Batch cook chilli con carne and freeze – it freezes beautifully and tastes better reheated'),
(40, 'Ask your butcher for beef short ribs – slow-cooked, they''re melt-in-the-mouth tender'),
(41, 'Store fresh celery wrapped in foil in the fridge – keeps it crisp for weeks'),
(42, 'Freeze leftover roast potatoes – reheat in the oven for almost-as-good-as-fresh'),
(43, 'Meal prep your breakfast smoothies – portion fruit and veg, freeze, blend with milk'),
(44, 'Your local market will have the freshest produce – shop early for best selection'),
(45, 'Store fresh carrots with tops removed in the fridge – they''ll last much longer'),
(46, 'Freeze leftover pasta sauce in portions – defrost overnight in the fridge'),
(47, 'Batch cook meatballs and freeze raw – cook from frozen, adding 5 minutes cooking time'),
(48, 'Ask your fishmonger for smoked haddock – perfect for fish pie or kedgeree'),
(49, 'Store fresh apples in the fridge – they''ll stay crisp for weeks'),
(50, 'Freeze leftover rice in portions – reheat with a splash of water in the microwave'),
(51, 'Meal prep your Sunday lunch prep – chop vegetables Saturday night, store in water'),
(52, 'Your local butcher can recommend best cuts for braising – perfect for winter'),
(53, 'Store fresh pears at room temperature to ripen, then refrigerate'),
(54, 'Freeze leftover cooked pasta – reheat by dropping into boiling water for 30 seconds'),
(55, 'Batch cook soup and freeze in portions – defrost overnight, heat for lunch'),
(56, 'Ask your butcher for pork belly – slow-roasted, it makes incredible crackling'),
(57, 'Store fresh cabbage in the fridge – it''ll keep for weeks if uncut'),
(58, 'Freeze leftover cooked vegetables – perfect for quick bubble and squeak'),
(59, 'Meal prep your week''s protein – cook chicken, beef, or pork, portion and refrigerate'),

-- March (Days 60-90) - Early spring, rhubarb season
(60, 'Rhubarb season starts now – ask your greengrocer for forced rhubarb, perfect for crumbles'),
(61, 'Ask your butcher for spring lamb – it''s at its best in March and April'),
(62, 'Store fresh rhubarb in the fridge wrapped in damp kitchen paper – use within a week'),
(63, 'Freeze rhubarb in chunks – perfect for crumbles and pies throughout the year'),
(64, 'Meal prep your spring cleaning meals – batch cook and freeze for busy days'),
(65, 'Your local farm shop will have the first spring greens – tender and delicious'),
(66, 'Store fresh spring onions upright in water in the fridge – they''ll keep growing'),
(67, 'Freeze leftover lamb in portions – perfect for quick shepherd''s pie'),
(68, 'Batch cook curry and freeze – Indian curries freeze beautifully and improve in flavour'),
(69, 'Ask your fishmonger for fresh cod – March is peak season for white fish'),
(70, 'Store fresh herbs from your greengrocer in water like flowers – change water daily'),
(71, 'Freeze leftover cooked rice in portions – reheat with a splash of water'),
(72, 'Meal prep your weekday breakfasts – overnight oats or chia pudding'),
(73, 'Your local butcher can recommend best cuts for Easter – plan ahead for the holiday'),
(74, 'Store fresh mushrooms in a paper bag in the fridge – never plastic'),
(75, 'Freeze leftover roast lamb – perfect for quick Monday night dinners'),
(76, 'Batch cook pasta sauces and freeze – tomato, meat, or vegetable-based all freeze well'),
(77, 'Ask your greengrocer for purple sprouting broccoli – it''s only in season briefly'),
(78, 'Store fresh asparagus upright in water in the fridge – use within 2-3 days'),
(79, 'Freeze leftover mashed potato in portions – perfect for quick fish cakes'),
(80, 'Meal prep your Sunday roast prep – chop vegetables Saturday, store in water'),
(81, 'Your local market will have the first spring vegetables – shop early for best selection'),
(82, 'Store fresh leeks wrapped in damp kitchen paper – they''ll keep for weeks'),
(83, 'Freeze leftover cooked vegetables – perfect for quick bubble and squeak'),
(84, 'Batch cook chilli and freeze in portions – it freezes beautifully'),
(85, 'Ask your butcher for beef brisket – perfect for slow-cooked Sunday roasts'),
(86, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(87, 'Freeze leftover gravy in ice cube trays – one cube per portion'),
(88, 'Meal prep your week''s lunches – make a big batch of soup or stew'),
(89, 'Your local fishmonger will have the freshest fish – ask what''s best today'),
(90, 'Store fresh herbs upright in water – change water every few days'),

-- April (Days 91-120) - Spring produce, asparagus
(91, 'Asparagus season begins – ask your greengrocer for British asparagus, it''s superior'),
(92, 'Ask your butcher for spring lamb – April is peak season for tender lamb'),
(93, 'Store fresh asparagus upright in water in the fridge – use within 2-3 days'),
(94, 'Freeze asparagus by blanching first – perfect for out-of-season use'),
(95, 'Meal prep your spring meals – lighter dishes perfect for warmer weather'),
(96, 'Your local farm shop will have the first new potatoes – waxy and delicious'),
(97, 'Store fresh new potatoes in a paper bag – don''t refrigerate, they''ll go sweet'),
(98, 'Freeze leftover roast lamb in portions – perfect for quick shepherd''s pie'),
(99, 'Batch cook spring vegetable soups and freeze – pea and mint, asparagus, watercress'),
(100, 'Ask your fishmonger for fresh salmon – April is peak season'),
(101, 'Store fresh herbs from your greengrocer in water – change water daily'),
(102, 'Freeze leftover cooked pasta – reheat by dropping into boiling water'),
(103, 'Meal prep your weekday breakfasts – overnight oats with fresh berries'),
(104, 'Your local butcher can recommend best cuts for Easter Sunday – book ahead'),
(105, 'Store fresh spring greens in the fridge – use within a few days'),
(106, 'Freeze leftover Easter lamb – perfect for quick midweek dinners'),
(107, 'Batch cook pasta sauces and freeze – all types freeze beautifully'),
(108, 'Ask your greengrocer for watercress – it''s at its peak in spring'),
(109, 'Store fresh watercress in water in the fridge – use within 2-3 days'),
(110, 'Freeze leftover mashed potato in portions – perfect for quick fish cakes'),
(111, 'Meal prep your Sunday lunch prep – chop vegetables Saturday night'),
(112, 'Your local market will have the best spring produce – shop early'),
(113, 'Store fresh rhubarb in the fridge wrapped in damp paper – use within a week'),
(114, 'Freeze rhubarb in chunks – perfect for crumbles throughout the year'),
(115, 'Batch cook curry and freeze – Indian curries improve after freezing'),
(116, 'Ask your butcher for pork shoulder – slow-cooked, it makes incredible pulled pork'),
(117, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(118, 'Freeze leftover gravy in ice cube trays – one cube per portion'),
(119, 'Meal prep your week''s protein – cook and portion for easy meals'),
(120, 'Your local fishmonger will have the freshest fish – ask what''s best'),

-- May (Days 121-151) - Late spring, strawberries start
(121, 'British strawberries start appearing – ask your greengrocer for local varieties'),
(122, 'Ask your butcher for spring lamb – May is still peak season'),
(123, 'Store fresh strawberries unwashed in the fridge – wash just before eating'),
(124, 'Freeze strawberries whole on a tray, then bag – perfect for smoothies and desserts'),
(125, 'Meal prep your summer meal planning – lighter dishes for warmer weather'),
(126, 'Your local farm shop will have the best seasonal produce – visit weekly'),
(127, 'Store fresh herbs upright in water – change water every few days'),
(128, 'Freeze leftover roast chicken in portions – perfect for quick salads'),
(129, 'Batch cook pasta sauces and freeze – tomato-based sauces freeze beautifully'),
(130, 'Ask your fishmonger for fresh mackerel – May is peak season'),
(131, 'Store fresh mackerel on ice in the fridge – use within 24 hours'),
(132, 'Freeze leftover cooked rice in portions – reheat with a splash of water'),
(133, 'Meal prep your weekday breakfasts – overnight oats with fresh fruit'),
(134, 'Your local butcher can recommend best cuts for barbecues – plan ahead'),
(135, 'Store fresh salad leaves wrapped in kitchen paper in the fridge'),
(136, 'Freeze leftover cooked pasta – reheat by dropping into boiling water'),
(137, 'Batch cook chilli and freeze – it freezes beautifully and improves in flavour'),
(138, 'Ask your greengrocer for British asparagus – it''s still in season'),
(139, 'Store fresh asparagus upright in water – use within 2-3 days'),
(140, 'Freeze asparagus by blanching first – perfect for out-of-season use'),
(141, 'Meal prep your Sunday lunch prep – chop vegetables Saturday night'),
(142, 'Your local market will have the best spring produce – shop early'),
(143, 'Store fresh new potatoes in a paper bag – don''t refrigerate'),
(144, 'Freeze leftover roast lamb in portions – perfect for quick dinners'),
(145, 'Batch cook soup and freeze – pea and mint is perfect for spring'),
(146, 'Ask your butcher for beef brisket – perfect for slow-cooked roasts'),
(147, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(148, 'Freeze leftover gravy in ice cube trays – one cube per portion'),
(149, 'Meal prep your week''s lunches – make a big batch of soup or salad'),
(150, 'Your local fishmonger will have the freshest fish – ask what''s best'),
(151, 'Store fresh herbs in water – change water daily for longest life'),

-- June (Days 152-181) - Summer begins, peak strawberries
(152, 'Peak strawberry season – ask your greengrocer for British strawberries, they''re unbeatable'),
(153, 'Ask your butcher for lamb chops – perfect for summer barbecues'),
(154, 'Store fresh strawberries unwashed in the fridge – wash just before eating'),
(155, 'Freeze strawberries whole on a tray, then bag – perfect for smoothies'),
(156, 'Meal prep your summer salads – prep vegetables, store separately, assemble fresh'),
(157, 'Your local farm shop will have the best summer produce – visit weekly'),
(158, 'Store fresh herbs upright in water – change water every few days'),
(159, 'Freeze leftover cooked chicken in portions – perfect for quick salads'),
(160, 'Batch cook pasta sauces and freeze – tomato-based sauces freeze beautifully'),
(161, 'Ask your fishmonger for fresh salmon – June is peak season'),
(162, 'Store fresh salmon on ice in the fridge – use within 24 hours'),
(163, 'Freeze leftover cooked rice in portions – reheat with a splash of water'),
(164, 'Meal prep your weekday breakfasts – overnight oats with fresh berries'),
(165, 'Your local butcher can recommend best cuts for barbecues – support local'),
(166, 'Store fresh salad leaves wrapped in kitchen paper in the fridge'),
(167, 'Freeze leftover cooked pasta – reheat by dropping into boiling water'),
(168, 'Batch cook curry and freeze – Indian curries freeze beautifully'),
(169, 'Ask your greengrocer for British raspberries – they''re starting to appear'),
(170, 'Store fresh raspberries in a single layer – they''re delicate and bruise easily'),
(171, 'Freeze raspberries whole on a tray, then bag – perfect for desserts'),
(172, 'Meal prep your Sunday lunch prep – chop vegetables Saturday night'),
(173, 'Your local market will have the best summer produce – shop early'),
(174, 'Store fresh new potatoes in a paper bag – don''t refrigerate'),
(175, 'Freeze leftover roast chicken in portions – perfect for quick meals'),
(176, 'Batch cook soup and freeze – gazpacho is perfect for summer'),
(177, 'Ask your butcher for pork shoulder – slow-cooked, it makes incredible pulled pork'),
(178, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(179, 'Freeze leftover gravy in ice cube trays – one cube per portion'),
(180, 'Meal prep your week''s protein – cook and portion for easy meals'),
(181, 'Your local fishmonger will have the freshest fish – ask what''s best'),

-- July (Days 182-212) - Peak summer produce
(182, 'Peak summer produce – ask your greengrocer for British tomatoes, they''re unbeatable'),
(183, 'Ask your butcher for beef burgers – perfect for summer barbecues'),
(184, 'Store fresh tomatoes at room temperature – never in the fridge, it ruins the flavour'),
(185, 'Freeze tomatoes whole – perfect for sauces and stews in winter'),
(186, 'Meal prep your summer meals – lighter dishes perfect for hot weather'),
(187, 'Your local farm shop will have the best seasonal produce – visit weekly'),
(188, 'Store fresh herbs upright in water – change water every few days'),
(189, 'Freeze leftover cooked chicken in portions – perfect for quick salads'),
(190, 'Batch cook pasta sauces and freeze – tomato-based sauces freeze beautifully'),
(191, 'Ask your fishmonger for fresh mackerel – July is peak season'),
(192, 'Store fresh mackerel on ice in the fridge – use within 24 hours'),
(193, 'Freeze leftover cooked rice in portions – reheat with a splash of water'),
(194, 'Meal prep your weekday breakfasts – overnight oats with fresh fruit'),
(195, 'Your local butcher can recommend best cuts for barbecues – support local businesses'),
(196, 'Store fresh salad leaves wrapped in kitchen paper in the fridge'),
(197, 'Freeze leftover cooked pasta – reheat by dropping into boiling water'),
(198, 'Batch cook curry and freeze – Indian curries freeze beautifully'),
(199, 'Ask your greengrocer for British courgettes – they''re abundant now'),
(200, 'Store fresh courgettes in the fridge – use within a week'),
(201, 'Freeze courgettes by slicing and blanching first – perfect for winter use'),
(202, 'Meal prep your Sunday lunch prep – chop vegetables Saturday night'),
(203, 'Your local market will have the best summer produce – shop early'),
(204, 'Store fresh berries in a single layer – they''re delicate and bruise easily'),
(205, 'Freeze berries whole on a tray, then bag – perfect for smoothies'),
(206, 'Batch cook soup and freeze – gazpacho is perfect for summer'),
(207, 'Ask your butcher for lamb chops – perfect for summer barbecues'),
(208, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(209, 'Freeze leftover gravy in ice cube trays – one cube per portion'),
(210, 'Meal prep your week''s lunches – make a big batch of salad'),
(211, 'Your local fishmonger will have the freshest fish – ask what''s best'),
(212, 'Store fresh herbs in water – change water daily for longest life'),

-- August (Days 213-243) - Late summer, blackberries
(213, 'Blackberry season begins – ask your greengrocer or forage locally, they''re free'),
(214, 'Ask your butcher for pork chops – perfect for late summer barbecues'),
(215, 'Store fresh blackberries in a single layer – they''re delicate and bruise easily'),
(216, 'Freeze blackberries whole on a tray, then bag – perfect for crumbles'),
(217, 'Meal prep your late summer meals – make the most of seasonal produce'),
(218, 'Your local farm shop will have the best seasonal produce – visit weekly'),
(219, 'Store fresh herbs upright in water – change water every few days'),
(220, 'Freeze leftover cooked chicken in portions – perfect for quick salads'),
(221, 'Batch cook pasta sauces and freeze – tomato-based sauces freeze beautifully'),
(222, 'Ask your fishmonger for fresh mackerel – August is still peak season'),
(223, 'Store fresh mackerel on ice in the fridge – use within 24 hours'),
(224, 'Freeze leftover cooked rice in portions – reheat with a splash of water'),
(225, 'Meal prep your weekday breakfasts – overnight oats with fresh berries'),
(226, 'Your local butcher can recommend best cuts for late summer barbecues'),
(227, 'Store fresh salad leaves wrapped in kitchen paper in the fridge'),
(228, 'Freeze leftover cooked pasta – reheat by dropping into boiling water'),
(229, 'Batch cook curry and freeze – Indian curries freeze beautifully'),
(230, 'Ask your greengrocer for British plums – they''re in season now'),
(231, 'Store fresh plums at room temperature to ripen, then refrigerate'),
(232, 'Freeze plums whole – perfect for crumbles and pies'),
(233, 'Meal prep your Sunday lunch prep – chop vegetables Saturday night'),
(234, 'Your local market will have the best late summer produce – shop early'),
(235, 'Store fresh tomatoes at room temperature – never in the fridge'),
(236, 'Freeze tomatoes whole – perfect for sauces in winter'),
(237, 'Batch cook soup and freeze – gazpacho is perfect for late summer'),
(238, 'Ask your butcher for beef burgers – perfect for barbecues'),
(239, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(240, 'Freeze leftover gravy in ice cube trays – one cube per portion'),
(241, 'Meal prep your week''s protein – cook and portion for easy meals'),
(242, 'Your local fishmonger will have the freshest fish – ask what''s best'),
(243, 'Store fresh herbs in water – change water daily for longest life'),

-- September (Days 244-273) - Autumn begins, game season
(244, 'Game season begins – ask your butcher for venison, pheasant, or partridge'),
(245, 'Ask your butcher for game birds – September is the start of the season'),
(246, 'Store fresh game birds in the fridge – use within 2-3 days'),
(247, 'Freeze game birds whole – they freeze beautifully and improve in flavour'),
(248, 'Meal prep your autumn meals – heartier dishes for cooler weather'),
(249, 'Your local farm shop will have the best seasonal produce – visit weekly'),
(250, 'Store fresh herbs upright in water – change water every few days'),
(251, 'Freeze leftover cooked game in portions – perfect for quick pies'),
(252, 'Batch cook pasta sauces and freeze – meat-based sauces freeze beautifully'),
(253, 'Ask your fishmonger for fresh mackerel – still in season'),
(254, 'Store fresh mackerel on ice in the fridge – use within 24 hours'),
(255, 'Freeze leftover cooked rice in portions – reheat with a splash of water'),
(256, 'Meal prep your weekday breakfasts – porridge is perfect for autumn'),
(257, 'Your local butcher can recommend best cuts for slow cooking – perfect for autumn'),
(258, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(259, 'Freeze leftover cooked pasta – reheat by dropping into boiling water'),
(260, 'Batch cook curry and freeze – Indian curries freeze beautifully'),
(261, 'Ask your greengrocer for British apples – they''re abundant now'),
(262, 'Store fresh apples in the fridge – they''ll stay crisp for weeks'),
(263, 'Freeze apples sliced – perfect for crumbles and pies'),
(264, 'Meal prep your Sunday lunch prep – chop vegetables Saturday night'),
(265, 'Your local market will have the best autumn produce – shop early'),
(266, 'Store fresh blackberries in a single layer – use quickly'),
(267, 'Freeze blackberries whole on a tray, then bag – perfect for crumbles'),
(268, 'Batch cook soup and freeze – butternut squash soup is perfect for autumn'),
(269, 'Ask your butcher for venison – it''s lean, flavourful, and in season'),
(270, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(271, 'Freeze leftover gravy in ice cube trays – one cube per portion'),
(272, 'Meal prep your week''s lunches – make a big batch of soup'),
(273, 'Your local fishmonger will have the freshest fish – ask what''s best'),

-- October (Days 274-304) - Autumn produce, pumpkins
(274, 'Pumpkin season – ask your greengrocer for British pumpkins, perfect for soups and pies'),
(275, 'Ask your butcher for beef brisket – perfect for slow-cooked autumn roasts'),
(276, 'Store fresh pumpkins in a cool, dark place – they''ll last for months'),
(277, 'Freeze pumpkin puree in portions – perfect for soups and pies'),
(278, 'Meal prep your autumn meals – hearty stews and casseroles'),
(279, 'Your local farm shop will have the best seasonal produce – visit weekly'),
(280, 'Store fresh herbs upright in water – change water every few days'),
(281, 'Freeze leftover cooked game in portions – perfect for quick pies'),
(282, 'Batch cook pasta sauces and freeze – meat-based sauces freeze beautifully'),
(283, 'Ask your fishmonger for fresh cod – October is peak season'),
(284, 'Store fresh cod on ice in the fridge – use within 24 hours'),
(285, 'Freeze leftover cooked rice in portions – reheat with a splash of water'),
(286, 'Meal prep your weekday breakfasts – porridge is perfect for autumn'),
(287, 'Your local butcher can recommend best cuts for slow cooking – perfect for autumn'),
(288, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(289, 'Freeze leftover cooked pasta – reheat by dropping into boiling water'),
(290, 'Batch cook curry and freeze – Indian curries freeze beautifully'),
(291, 'Ask your greengrocer for British pears – they''re in season now'),
(292, 'Store fresh pears at room temperature to ripen, then refrigerate'),
(293, 'Freeze pears sliced – perfect for crumbles and pies'),
(294, 'Meal prep your Sunday lunch prep – chop vegetables Saturday night'),
(295, 'Your local market will have the best autumn produce – shop early'),
(296, 'Store fresh apples in the fridge – they''ll stay crisp for weeks'),
(297, 'Freeze apples sliced – perfect for crumbles and pies'),
(298, 'Batch cook soup and freeze – butternut squash soup is perfect for autumn'),
(299, 'Ask your butcher for venison – it''s lean, flavourful, and in season'),
(300, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(301, 'Freeze leftover gravy in ice cube trays – one cube per portion'),
(302, 'Meal prep your week''s lunches – make a big batch of soup'),
(303, 'Your local fishmonger will have the freshest fish – ask what''s best'),
(304, 'Store fresh herbs in water – change water daily for longest life'),

-- November (Days 305-334) - Late autumn, comfort foods
(305, 'Bonfire Night – ask your butcher for sausages, perfect for hot dogs'),
(306, 'Ask your butcher for beef brisket – perfect for slow-cooked Sunday roasts'),
(307, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(308, 'Freeze leftover roast beef in portions – perfect for quick sandwiches'),
(309, 'Meal prep your winter meals – hearty stews and casseroles'),
(310, 'Your local farm shop will have the best seasonal produce – visit weekly'),
(311, 'Store fresh herbs upright in water – change water every few days'),
(312, 'Freeze leftover cooked game in portions – perfect for quick pies'),
(313, 'Batch cook pasta sauces and freeze – meat-based sauces freeze beautifully'),
(314, 'Ask your fishmonger for fresh cod – November is peak season'),
(315, 'Store fresh cod on ice in the fridge – use within 24 hours'),
(316, 'Freeze leftover cooked rice in portions – reheat with a splash of water'),
(317, 'Meal prep your weekday breakfasts – porridge is perfect for winter'),
(318, 'Your local butcher can recommend best cuts for slow cooking – perfect for winter'),
(319, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(320, 'Freeze leftover cooked pasta – reheat by dropping into boiling water'),
(321, 'Batch cook curry and freeze – Indian curries freeze beautifully'),
(322, 'Ask your greengrocer for British Brussels sprouts – they''re at their best now'),
(323, 'Store fresh Brussels sprouts in the fridge – use within a week'),
(324, 'Freeze Brussels sprouts by blanching first – perfect for Christmas prep'),
(325, 'Meal prep your Sunday lunch prep – chop vegetables Saturday night'),
(326, 'Your local market will have the best autumn produce – shop early'),
(327, 'Store fresh apples in the fridge – they''ll stay crisp for weeks'),
(328, 'Freeze apples sliced – perfect for crumbles and pies'),
(329, 'Batch cook soup and freeze – butternut squash soup is perfect for winter'),
(330, 'Ask your butcher for venison – it''s lean, flavourful, and in season'),
(331, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(332, 'Freeze leftover gravy in ice cube trays – one cube per portion'),
(333, 'Meal prep your week''s lunches – make a big batch of soup'),
(334, 'Your local fishmonger will have the freshest fish – ask what''s best'),

-- December (Days 335-365) - Winter, Christmas preparations
(335, 'Christmas prep begins – ask your butcher to order your turkey early'),
(336, 'Ask your butcher for beef brisket – perfect for Christmas Eve dinner'),
(337, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(338, 'Freeze leftover Christmas turkey in portions – perfect for quick curries'),
(339, 'Meal prep your Christmas vegetables – prep ahead to reduce stress'),
(340, 'Your local farm shop will have the best seasonal produce – visit weekly'),
(341, 'Store fresh herbs upright in water – change water every few days'),
(342, 'Freeze leftover Christmas pudding – it freezes beautifully'),
(343, 'Batch cook mince pies and freeze – bake from frozen, adding 5 minutes'),
(344, 'Ask your fishmonger for fresh salmon – perfect for Christmas Eve'),
(345, 'Store fresh salmon on ice in the fridge – use within 24 hours'),
(346, 'Freeze leftover cooked rice in portions – reheat with a splash of water'),
(347, 'Meal prep your Christmas breakfast – prep everything Christmas Eve'),
(348, 'Your local butcher can recommend best cuts for Christmas – book early'),
(349, 'Store fresh Brussels sprouts in the fridge – use within a week'),
(350, 'Freeze Brussels sprouts by blanching first – perfect for Christmas Day'),
(351, 'Batch cook Christmas sides and freeze – roast potatoes freeze well'),
(352, 'Ask your greengrocer for British parsnips – they''re at their best now'),
(353, 'Store fresh parsnips in a cool, dark place – they''ll last for weeks'),
(354, 'Freeze parsnips by blanching first – perfect for Christmas prep'),
(355, 'Meal prep your Christmas Day prep – chop vegetables Christmas Eve'),
(356, 'Your local market will have the best winter produce – shop early'),
(357, 'Store fresh root vegetables in a cool, dark place – they''ll last months'),
(358, 'Freeze leftover Christmas gravy in ice cube trays – one cube per portion'),
(359, 'Batch cook soup and freeze – perfect for post-Christmas meals'),
(360, 'Ask your butcher for gammon – perfect for Boxing Day'),
(361, 'Store fresh gammon in the fridge – use within the use-by date'),
(362, 'Freeze leftover Christmas ham in portions – perfect for sandwiches'),
(363, 'Meal prep your New Year meals – batch cook and freeze for January'),
(364, 'Your local fishmonger will have the freshest fish – ask what''s best'),
(365, 'End the year by supporting your local butcher, greengrocer, and fishmonger – they make British food great');

