-- Create daily cooking tips table
CREATE TABLE public.daily_cooking_tips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  day_of_year integer UNIQUE NOT NULL,
  tip text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Add constraint as trigger instead of CHECK to avoid immutability issues
CREATE OR REPLACE FUNCTION validate_day_of_year()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.day_of_year < 1 OR NEW.day_of_year > 365 THEN
    RAISE EXCEPTION 'day_of_year must be between 1 and 365';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER check_day_of_year_range
  BEFORE INSERT OR UPDATE ON public.daily_cooking_tips
  FOR EACH ROW
  EXECUTE FUNCTION validate_day_of_year();

-- Enable RLS
ALTER TABLE public.daily_cooking_tips ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read tips
CREATE POLICY "Anyone can view daily tips"
  ON public.daily_cooking_tips
  FOR SELECT
  TO authenticated
  USING (true);

-- Insert 365 UK-specific cooking tips
INSERT INTO public.daily_cooking_tips (day_of_year, tip) VALUES
(1, 'Start the year by organising your spice cupboard – group by cuisine type for easier meal planning'),
(2, 'Save vegetable peelings in the freezer to make homemade stock – waste not, want not'),
(3, 'Season cast iron pans with a thin layer of oil after each wash to maintain their non-stick surface'),
(4, 'Freeze leftover wine in ice cube trays for adding flavour to sauces and stews'),
(5, 'Store fresh herbs upright in a glass of water in the fridge, like a bouquet'),
(6, 'Add a pinch of bicarbonate of soda to tomato sauce to reduce acidity'),
(7, 'Roast your Sunday vegetables at 200°C for the perfect crispy edges'),
(8, 'Keep a batch of Yorkshire pudding batter in the fridge – it improves after resting overnight'),
(9, 'Salt aubergines before cooking to remove bitterness and reduce oil absorption'),
(10, 'Make your own breadcrumbs from stale bread – much tastier than shop-bought'),
(11, 'Add a bay leaf to your pasta water for subtle flavour enhancement'),
(12, 'Rest meat for half the cooking time before slicing for maximum juiciness'),
(13, 'Sharpen kitchen knives regularly – a sharp knife is safer than a blunt one'),
(14, 'Cook rice using the absorption method: 1 part rice to 2 parts water, perfect every time'),
(15, 'Add a splash of milk to scrambled eggs just before they finish cooking for extra creaminess'),
(16, 'Store potatoes in a cool, dark place away from onions to prevent sprouting'),
(17, 'Make crispy roast potatoes by parboiling first, then roughing up the edges before roasting'),
(18, 'Use the pasta cooking water to thin and bind your sauce – it''s liquid gold'),
(19, 'Keep a well-stocked freezer with batch-cooked meals for those busy weeknights'),
(20, 'Toast spices in a dry pan before grinding to release their essential oils'),
(21, 'Add a teaspoon of sugar to tomato-based sauces to balance acidity'),
(22, 'Cook fish with the skin on to keep it moist and add extra flavour'),
(23, 'Use leftover roast chicken to make a hearty soup or pie filling'),
(24, 'Keep fresh ginger in the freezer and grate it straight from frozen'),
(25, 'Add a splash of vinegar to poaching water to help eggs hold their shape'),
(26, 'Make your own curry paste in bulk and freeze in portions'),
(27, 'Use a potato ricer for the fluffiest mashed potato you''ve ever tasted'),
(28, 'Blanch green vegetables in boiling salted water, then refresh in ice water to keep the colour vibrant'),
(29, 'Store fresh mushrooms in a paper bag, never plastic, to prevent them going slimy'),
(30, 'Add a strip of lemon zest to your gravy for a subtle citrus lift'),
(31, 'Make double the amount of bolognese and freeze half for an easy midweek meal'),
(32, 'Use the back of a spoon to peel ginger – it''s easier and wastes less'),
(33, 'Bring eggs to room temperature before baking for better rise and texture'),
(34, 'Cook bacon in the oven at 180°C for perfectly crispy rashers without the splatter'),
(35, 'Add a splash of boiling water from the kettle to speed up bringing pots to the boil'),
(36, 'Store fresh coriander with roots in water and cover with a plastic bag in the fridge'),
(37, 'Make your own stock from roast chicken carcasses – freeze in portions for later use'),
(38, 'Use a damp tea towel under your chopping board to stop it slipping'),
(39, 'Add Marmite to beef stews and casseroles for extra umami depth'),
(40, 'Cook mushrooms without stirring initially to get a good caramelised colour'),
(41, 'Store bananas separately from other fruit to prevent everything ripening too quickly'),
(42, 'Make garlic bread using proper butter, not margarine, for the best flavour'),
(43, 'Add a pinch of nutmeg to white sauces and mashed potato for warmth'),
(44, 'Use kitchen scissors to snip fresh herbs straight into dishes'),
(45, 'Cook onions low and slow for sweetness – rushing them makes them bitter'),
(46, 'Keep a supply of frozen peas – they''re just as nutritious as fresh and always available'),
(47, 'Add Worcester sauce to shepherd''s pie mince for extra savoury depth'),
(48, 'Use a fish slice to flip delicate foods – it''s designed for the job'),
(49, 'Make breadcrumb toppings with a mix of panko and traditional breadcrumbs for extra crunch'),
(50, 'Store fresh basil at room temperature in water, not the fridge'),
(51, 'Add a tablespoon of vinegar to the water when poaching fish to keep it firm'),
(52, 'Use a mandoline for perfectly uniform vegetable slices – but mind your fingers'),
(53, 'Cook sausages slowly over medium heat for even cooking and crispy skin'),
(54, 'Save Parmesan rinds to add to soups and stews for extra flavour'),
(55, 'Make your own salad dressings – they''re fresher and you control the ingredients'),
(56, 'Store fresh asparagus upright in water like flowers'),
(57, 'Add a pinch of sugar to cooked carrots to enhance their natural sweetness'),
(58, 'Use buttermilk in scone recipes for the lightest, fluffiest texture'),
(59, 'Cook pasta just until al dente – it''ll continue cooking when mixed with hot sauce'),
(60, 'Keep a bag of frozen prawns for quick weeknight stir-fries and pasta dishes'),
(61, 'Add a splash of cream to scrambled eggs at the start of cooking for extra richness'),
(62, 'Use the water from cooked chickpeas (aquafaba) as an egg white substitute in baking'),
(63, 'Store fresh lemons in water in the fridge to keep them juicy for longer'),
(64, 'Make crispy bacon by starting it in a cold pan – no need to preheat'),
(65, 'Add dried mushrooms to beef dishes for instant umami depth'),
(66, 'Use a slotted spoon to skim foam from stocks and soups'),
(67, 'Cook courgettes quickly over high heat to prevent them becoming watery'),
(68, 'Store fresh parsley in a sealed bag with a piece of kitchen paper to absorb moisture'),
(69, 'Add a splash of sherry to French onion soup for authentic flavour'),
(70, 'Use parchment paper when rolling pastry to prevent sticking without adding flour'),
(71, 'Make vegetable crisps from root vegetables for healthy snacking'),
(72, 'Store tomatoes at room temperature for the best flavour – never in the fridge'),
(73, 'Add a teaspoon of English mustard to cheese sauces for extra punch'),
(74, 'Use a pizza stone in your oven for crispier pizza bases'),
(75, 'Cook jacket potatoes at 200°C for the fluffiest insides and crispiest skins'),
(76, 'Save bacon fat to use for roasting potatoes – incredible flavour'),
(77, 'Add fresh lemon juice to guacamole to prevent browning'),
(78, 'Use a tea towel between pot and lid to catch condensation and keep rice fluffy'),
(79, 'Store spring onions with roots in water on the windowsill – they''ll keep growing'),
(80, 'Make your own pesto and freeze in ice cube trays for portion control'),
(81, 'Add a splash of milk to omelettes for a fluffier texture'),
(82, 'Use day-old bread for the best bread and butter pudding'),
(83, 'Cook porridge with half milk, half water for the creamiest consistency'),
(84, 'Store fresh bread cut-side down on a wooden board to keep it fresh'),
(85, 'Add a pinch of cayenne to hot chocolate for warming spice'),
(86, 'Use a proper meat thermometer to ensure chicken is cooked through'),
(87, 'Make iced coffee from leftover morning coffee rather than letting it go to waste'),
(88, 'Store avocados with an onion in a sealed container to prevent browning'),
(89, 'Add lemon zest to cake batters for extra citrus flavour without adding liquid'),
(90, 'Use the finest grater for hard cheese – it goes further and melts better'),
(91, 'Cook green beans until just tender – they should still have a slight bite'),
(92, 'Store fresh mint in water in the fridge, changing the water every few days'),
(93, 'Add a splash of brandy to Christmas cake and pudding for authentic festive flavour'),
(94, 'Use a pastry brush to glaze pastries with beaten egg for a golden finish'),
(95, 'Make croutons from stale bread with olive oil, garlic, and herbs'),
(96, 'Store fresh strawberries unwashed in the fridge and wash just before eating'),
(97, 'Add a tablespoon of cornflour to fruit crumbles to thicken the juice'),
(98, 'Use a kitchen blowtorch for perfect crème brûlée every time'),
(99, 'Cook cauliflower cheese with a mixture of cheddar and parmesan for depth'),
(100, 'Store fresh blueberries in a single layer to prevent them crushing'),
(101, 'Add a bay leaf to rice while cooking for subtle aromatic flavour'),
(102, 'Use Greek yoghurt as a healthier alternative to sour cream'),
(103, 'Cook beetroot in the oven wrapped in foil for intense, earthy sweetness'),
(104, 'Store fresh lettuce wrapped in kitchen paper to keep it crisp'),
(105, 'Add a splash of red wine to beef bourguignon for authentic French flavour'),
(106, 'Use a spiralizer to make vegetable noodles for low-carb dishes'),
(107, 'Cook sweetcorn in boiling water with a splash of milk for extra sweetness'),
(108, 'Store fresh raspberries in a single layer – they''re delicate and bruise easily'),
(109, 'Add a teaspoon of Dijon mustard to vinaigrettes for emulsification'),
(110, 'Use a digital scale for baking – it''s far more accurate than cup measurements'),
(111, 'Cook fish and chips with proper beef dripping for authentic chippy flavour'),
(112, 'Store fresh broccoli in the fridge unwashed and use within a few days'),
(113, 'Add a splash of balsamic vinegar to strawberries to intensify their sweetness'),
(114, 'Use a griddle pan for perfect char marks on vegetables and meat'),
(115, 'Cook toad in the hole with the batter at room temperature for better rise'),
(116, 'Store fresh spinach in a sealed bag with kitchen paper to absorb moisture'),
(117, 'Add a pinch of saffron to fish pie for luxurious colour and flavour'),
(118, 'Use a microplane to zest citrus fruits for fine, flavourful shavings'),
(119, 'Cook bubble and squeak with leftover mash and vegetables from Sunday dinner'),
(120, 'Store fresh apples in the fridge to keep them crisp for weeks'),
(121, 'Add a teaspoon of golden syrup to gingerbread for authentic British flavour'),
(122, 'Use a food processor to make pastry – it''s quick and prevents overworking'),
(123, 'Cook leeks slowly in butter until meltingly soft for the best flavour'),
(124, 'Store fresh pears at room temperature to ripen, then refrigerate'),
(125, 'Add a splash of elderflower cordial to summer fruit salads'),
(126, 'Use proper sea salt for finishing dishes – the flakes add lovely texture'),
(127, 'Cook black pudding gently to prevent it breaking apart'),
(128, 'Store fresh celery wrapped in foil in the fridge to keep it crisp'),
(129, 'Add fresh thyme to roasted root vegetables for earthy, aromatic flavour'),
(130, 'Use a proper fish kettle for poaching whole salmon'),
(131, 'Cook hot cross buns from scratch this Easter – the smell is divine'),
(132, 'Store fresh cherries in the fridge and eat within a few days'),
(133, 'Add a splash of Pimm''s to summer fruit salads for a British twist'),
(134, 'Use a proper mortar and pestle for grinding spices – it makes a difference'),
(135, 'Cook lamb with rosemary and garlic for classic British Sunday roast'),
(136, 'Store fresh figs in the fridge and eat quickly as they perish fast'),
(137, 'Add a pinch of ground cloves to apple crumble for warming spice'),
(138, 'Use double cream for the richest mashed potato you''ve ever tasted'),
(139, 'Cook kippers under the grill for a proper British breakfast'),
(140, 'Store fresh plums at room temperature until ripe, then refrigerate'),
(141, 'Add fresh sage to brown butter for a classic pasta sauce'),
(142, 'Use a proper whisk for making lump-free gravy'),
(143, 'Cook game properly – it should be pink in the middle, never overcooked'),
(144, 'Store fresh grapes in the fridge unwashed in a perforated bag'),
(145, 'Add a splash of sloe gin to your winter puddings'),
(146, 'Use a proper steamer for perfectly cooked vegetables that retain nutrients'),
(147, 'Cook haggis according to packet instructions – it''s easier than you think'),
(148, 'Store fresh peaches at room temperature to ripen properly'),
(149, 'Add Guinness to beef and mushroom pie for rich, malty depth'),
(150, 'Use a proper jam thermometer when making preserves'),
(151, 'Cook proper fish pie with smoked haddock for authentic flavour'),
(152, 'Store fresh nectarines at room temperature until fragrant and slightly soft'),
(153, 'Add a splash of port to your gravy for Sunday roast'),
(154, 'Use a proper rolling pin, not a wine bottle, for best pastry results'),
(155, 'Cook oxtail low and slow until the meat falls off the bone'),
(156, 'Store fresh apricots at room temperature to ripen, then eat quickly'),
(157, 'Add a teaspoon of Coleman''s mustard powder to cheese scones'),
(158, 'Use proper beef suet for the lightest steamed puddings'),
(159, 'Cook tripe and onions the traditional way for authentic British comfort food'),
(160, 'Store fresh mangoes at room temperature until fragrant'),
(161, 'Add fresh tarragon to chicken dishes for French-inspired flavour'),
(162, 'Use a proper pudding basin for steamed sponge puddings'),
(163, 'Cook steak and kidney pudding for hours – the long cooking is essential'),
(164, 'Store fresh pineapple at room temperature for a day to increase sweetness'),
(165, 'Add a splash of Drambuie to bread and butter pudding'),
(166, 'Use a proper pressure cooker for quick, tender stews'),
(167, 'Cook cottage pie with proper mince, not pre-packaged mince with gristle'),
(168, 'Store fresh melons at room temperature until ripe, then refrigerate'),
(169, 'Add fresh chives to mashed potato and sour cream for a classic combination'),
(170, 'Use a proper jelly mould for setting summer puddings'),
(171, 'Cook proper Cumberland sausage in a coil, not pre-cut links'),
(172, 'Store fresh kiwi fruit at room temperature to ripen'),
(173, 'Add a splash of cider to pork casseroles for West Country flavour'),
(174, 'Use a proper flan tin with a removable base for neat tarts'),
(175, 'Cook devilled kidneys on toast for a traditional Victorian breakfast'),
(176, 'Store fresh papaya at room temperature until the skin yields slightly'),
(177, 'Add fresh oregano to tomato-based dishes at the end of cooking'),
(178, 'Use a proper loaf tin for even rising in bread baking'),
(179, 'Cook Welsh rarebit under a hot grill for a bubbling, golden topping'),
(180, 'Store fresh passion fruit at room temperature until wrinkled'),
(181, 'Add a teaspoon of Marmite to your beef stock for extra savouriness'),
(182, 'Use a proper cake tin liner for even baking and easy removal'),
(183, 'Cook Scotch eggs with properly seasoned sausage meat'),
(184, 'Store fresh dragon fruit in the fridge once ripe'),
(185, 'Add fresh dill to fish dishes and cucumber salad'),
(186, 'Use a proper brioche tin for the traditional fluted shape'),
(187, 'Cook proper pork pies with hot water crust pastry'),
(188, 'Store fresh lychees in the fridge and eat within a week'),
(189, 'Add a pinch of mace to béchamel sauce for subtle warmth'),
(190, 'Use a proper terrine mould for making pâté'),
(191, 'Cook proper Lancashire hotpot with lamb neck and kidneys'),
(192, 'Store fresh pomegranates at room temperature for up to a week'),
(193, 'Add fresh rosemary to roasted lamb for classic pairing'),
(194, 'Use a proper bain-marie for gentle cooking of delicate sauces'),
(195, 'Cook proper steak and ale pie with a good British bitter'),
(196, 'Store fresh persimmons at room temperature until very soft'),
(197, 'Add fresh marjoram to Italian-inspired dishes'),
(198, 'Use a proper proving basket for artisan bread making'),
(199, 'Cook proper angels on horseback with fresh oysters and bacon'),
(200, 'Store fresh guava at room temperature until fragrant'),
(201, 'Add fresh lovage to soups and stews for celery-like flavour'),
(202, 'Use a proper banneton for sourdough bread proving'),
(203, 'Cook proper devils on horseback with prunes and bacon'),
(204, 'Store fresh star fruit at room temperature until edges brown slightly'),
(205, 'Add fresh chervil to delicate fish dishes'),
(206, 'Use a proper roasting tin with a rack for even air circulation'),
(207, 'Cook proper jugged hare with port and redcurrant jelly'),
(208, 'Store fresh kumquats in the fridge and eat skin and all'),
(209, 'Add fresh lemon balm to summer drinks and desserts'),
(210, 'Use a proper baking stone for crispy-bottomed pizzas'),
(211, 'Cook proper potted shrimps with plenty of butter and mace'),
(212, 'Store fresh rhubarb in the fridge wrapped in foil'),
(213, 'Add fresh sorrel to soups for a lemony tang'),
(214, 'Use a proper fish slice for serving whole fish'),
(215, 'Cook proper finnan haddie with milk and butter'),
(216, 'Store fresh gooseberries in the fridge and use quickly'),
(217, 'Add fresh borage flowers to summer drinks'),
(218, 'Use a proper asparagus steamer for perfectly cooked spears'),
(219, 'Cook proper Arbroath smokies by grilling them gently'),
(220, 'Store fresh redcurrants in the fridge and use within days'),
(221, 'Add fresh hyssop to game dishes for a minty, anise flavour'),
(222, 'Use a proper lobster cracker for easier eating'),
(223, 'Cook proper dressed crab with plenty of brown meat'),
(224, 'Store fresh blackcurrants in the fridge and freeze what you won''t use'),
(225, 'Add fresh salad burnet to green salads for cucumber flavour'),
(226, 'Use a proper oyster knife for safe shucking'),
(227, 'Cook proper potted char with butter and anchovy essence'),
(228, 'Store fresh whitecurrants in the fridge – they''re delicate'),
(229, 'Add fresh sweet cicely to reduce tartness in fruit dishes'),
(230, 'Use a proper snail fork and tongs for escargot'),
(231, 'Cook proper soused herrings with vinegar and spices'),
(232, 'Store fresh elderberries in the fridge and cook before eating'),
(233, 'Add fresh fennel fronds to fish dishes for aniseed notes'),
(234, 'Use a proper lobster pick for extracting all the meat'),
(235, 'Cook proper jellied eels with white pepper and nutmeg'),
(236, 'Store fresh sloes in the freezer before making sloe gin'),
(237, 'Add fresh summer savory to bean dishes'),
(238, 'Use a proper caviar spoon – never silver, which affects the taste'),
(239, 'Cook proper Cullen skink with Finnan haddie and potatoes'),
(240, 'Store fresh damsons in the fridge and use for jams'),
(241, 'Add fresh winter savory to hearty stews'),
(242, 'Use a proper crab pick for extracting meat from shells'),
(243, 'Cook proper cock-a-leekie with prunes for authentic Scottish flavour'),
(244, 'Store fresh rowans in the freezer – they''re too bitter raw'),
(245, 'Add fresh rue sparingly to salads – it''s very strong'),
(246, 'Use a proper mussel pot with a steaming basket'),
(247, 'Cook proper Partan bree with crab and rice'),
(248, 'Store fresh crab apples in the fridge for jelly making'),
(249, 'Add fresh alexanders to spring dishes as a parsley substitute'),
(250, 'Use a proper periwinkle pin for extracting the meat'),
(251, 'Cook proper stoved chicken with potatoes and onions'),
(252, 'Store fresh sea buckthorn berries in the freezer'),
(253, 'Add fresh Good King Henry to dishes like spinach'),
(254, 'Use a proper cockle rake for safe foraging'),
(255, 'Cook proper rumbledethumps with cabbage, potato, and cheese'),
(256, 'Store fresh wild garlic leaves wrapped in damp kitchen paper'),
(257, 'Add fresh samphire to fish dishes for a salty crunch'),
(258, 'Use a proper winkle pin for extracting the meat'),
(259, 'Cook proper clapshot with turnip, potato, and chives'),
(260, 'Store fresh horseradish root in the fridge wrapped in damp paper'),
(261, 'Add fresh penny buns (porcini) to autumn dishes'),
(262, 'Use a proper chanterelle knife with a brush for cleaning mushrooms'),
(263, 'Cook proper skirlie as a side dish or stuffing'),
(264, 'Store fresh wild mushrooms in paper bags, never plastic'),
(265, 'Add fresh chanterelles to autumn dishes while they''re in season'),
(266, 'Use a proper foraging basket with spaces for air circulation'),
(267, 'Cook proper haggis, neeps, and tatties for Burns Night'),
(268, 'Store fresh nettles with gloves and blanch before using'),
(269, 'Add fresh morels to spring dishes – they''re incredibly flavourful'),
(270, 'Use a proper game bag for carrying foraged goods'),
(271, 'Cook proper Scotch broth with pearl barley and root vegetables'),
(272, 'Store fresh dandelion leaves in the fridge and use young leaves'),
(273, 'Add fresh trompettes to autumn dishes for deep, rich flavour'),
(274, 'Use a proper mushroom knife with a brush attachment'),
(275, 'Cook proper Forfar bridies with proper shortcrust pastry'),
(276, 'Store fresh chickweed in the fridge – it wilts quickly'),
(277, 'Add fresh hedgehog mushrooms to autumn casseroles'),
(278, 'Use a proper game knife for preparing wild meat'),
(279, 'Cook proper Selkirk bannock with fruit and butter'),
(280, 'Store fresh fat hen like spinach and use quickly'),
(281, 'Add fresh beech mushrooms to stir-fries'),
(282, 'Use a proper game shears for jointing birds'),
(283, 'Cook proper Edinburgh fog with cream and meringue'),
(284, 'Store fresh jack-by-the-hedge in the fridge for a few days'),
(285, 'Add fresh velvet shanks to winter stews'),
(286, 'Use a proper barding needle for threading bacon through game'),
(287, 'Cook proper Atholl brose with oats, honey, and whisky'),
(288, 'Store fresh hairy bittercress in the fridge – it''s peppery'),
(289, 'Add fresh oyster mushrooms to Asian-inspired dishes'),
(290, 'Use a proper larding needle for adding fat to lean game'),
(291, 'Cook proper cranachan with raspberries, oats, and cream'),
(292, 'Store fresh ground elder young leaves and cook like spinach'),
(293, 'Add fresh enoki mushrooms to broths and soups'),
(294, 'Use a proper game saw for cutting through bone'),
(295, 'Cook proper clootie dumpling with dried fruit and spices'),
(296, 'Store fresh wood sorrel in the fridge and use the lemony leaves'),
(297, 'Add fresh shiitake mushrooms to Asian dishes'),
(298, 'Use a proper butcher''s steel to keep your knives sharp'),
(299, 'Cook proper tablet with condensed milk for authentic Scottish sweetness'),
(300, 'Store fresh wild strawberries carefully – they''re tiny and delicate'),
(301, 'Add fresh maitake mushrooms to hearty autumn dishes'),
(302, 'Use a proper cleaver for preparing meat and poultry'),
(303, 'Cook proper Dundee cake with almonds on top'),
(304, 'Store fresh bilberries in the fridge and use like blueberries'),
(305, 'Add fresh lion''s mane mushrooms to seafood dishes'),
(306, 'Use a proper boning knife for removing bones from meat'),
(307, 'Cook proper black bun for Hogmanay celebrations'),
(308, 'Store fresh cloudberries in the freezer if you''re lucky enough to find them'),
(309, 'Add fresh cep mushrooms to Italian-inspired dishes'),
(310, 'Use a proper filleting knife for preparing fish'),
(311, 'Cook proper pan haggarty with potatoes, onions, and cheese'),
(312, 'Store fresh ramsons (wild garlic) bulbs like regular garlic'),
(313, 'Add fresh puffballs to any mushroom dish while they''re pure white inside'),
(314, 'Use a proper salmon knife for slicing smoked fish'),
(315, 'Cook proper singing hinny on a griddle for authentic texture'),
(316, 'Store fresh crow garlic like spring onions'),
(317, 'Add fresh parasol mushrooms to autumnal dishes'),
(318, 'Use a proper carving knife and fork for Sunday roasts'),
(319, 'Cook proper stottie cake on a griddle, not in the oven'),
(320, 'Store fresh wild chives in the fridge wrapped in damp paper'),
(321, 'Add fresh honey fungus to soups after proper preparation'),
(322, 'Use a proper electric knife for even carving'),
(323, 'Cook proper pease pudding to serve with ham'),
(324, 'Store fresh wild thyme dried for winter use'),
(325, 'Add fresh shaggy ink caps while they''re young and firm'),
(326, 'Use a proper poultry shears for jointing chicken'),
(327, 'Cook proper pan haggerty in a cast iron skillet'),
(328, 'Store fresh wild marjoram dried for year-round use'),
(329, 'Add fresh wood ear mushrooms to Asian soups'),
(330, 'Use a proper kitchen scissors for herbs and small tasks'),
(331, 'Cook proper singin'' hinnie with currants and lard'),
(332, 'Store fresh wild oregano dried and use sparingly'),
(333, 'Add fresh cauliflower fungus to autumn dishes'),
(334, 'Use a proper mandoline with safety guard'),
(335, 'Cook proper Cornish pasties with proper crimping on the side'),
(336, 'Store fresh sea beet like chard and use the leaves'),
(337, 'Add fresh chicken of the woods to vegetarian dishes for a meaty texture'),
(338, 'Use a proper speed peeler for efficient vegetable preparation'),
(339, 'Cook proper hevva cake for Cornish tea'),
(340, 'Store fresh glasswort in the fridge and use quickly'),
(341, 'Add fresh bay boletes to hearty autumn dishes'),
(342, 'Use a proper julienne peeler for uniform vegetable strips'),
(343, 'Cook proper saffron buns with proper Cornish saffron'),
(344, 'Store fresh orache like spinach and use young leaves'),
(345, 'Add fresh amethyst deceivers to autumn casseroles'),
(346, 'Use a proper channel knife for citrus zesting'),
(347, 'Cook proper stargazey pie with pilchards poking through'),
(348, 'Store fresh sea purslane in the fridge for a few days'),
(349, 'Add fresh wood blewits to late autumn dishes'),
(350, 'Use a proper apple corer for neat preparation'),
(351, 'Cook proper Dorset apple cake with chunks of apple'),
(352, 'Store fresh marsh samphire in the fridge and eat fresh'),
(353, 'Add fresh field blewits to mushroom medleys'),
(354, 'Use a proper cherry pitter for efficient preparation'),
(355, 'Cook proper Lardy cake with plenty of lard and sugar'),
(356, 'Store fresh rock samphire pickled in vinegar'),
(357, 'Add fresh St George''s mushrooms to spring dishes'),
(358, 'Use a proper melon baller for neat fruit presentation'),
(359, 'Cook proper Bath buns with crushed sugar on top'),
(360, 'Store fresh sea lettuce in the fridge for a few days'),
(361, 'Add fresh fairy ring champignons to autumn dishes'),
(362, 'Use a proper egg slicer for uniform slices'),
(363, 'Cook proper Sally Lunns in Bath – they''re best fresh'),
(364, 'Store fresh dulse dried for adding to soups and stews'),
(365, 'End the year by trying one new recipe you''ve been putting off – you might discover a new favourite');