-- Add drink pairing columns to recipes table
-- These are generated by AI when recipes are created/imported

ALTER TABLE recipes 
ADD COLUMN IF NOT EXISTS alcoholic_pairing TEXT,
ADD COLUMN IF NOT EXISTS non_alcoholic_pairing TEXT;

-- Add the same columns to public_recipe_shares for shared recipes
ALTER TABLE public_recipe_shares 
ADD COLUMN IF NOT EXISTS alcoholic_pairing TEXT,
ADD COLUMN IF NOT EXISTS non_alcoholic_pairing TEXT;

-- Add comment for documentation
COMMENT ON COLUMN recipes.alcoholic_pairing IS 'AI-generated wine, beer, or cocktail pairing suggestion';
COMMENT ON COLUMN recipes.non_alcoholic_pairing IS 'AI-generated non-alcoholic beverage pairing suggestion';
